version: '2'
services:
  webapp:
    container_name: tript_webapp
    build: .
    command: sh -c 'npm install --production; bower install --allow-root; npm start'
    volumes:
      - .:/app
    ports:
      - 8100:8100
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DOCKER_ENV=true
